### ISSUE TITLE
個人ゲノムゲートウェイの追加のニュース

### ISSUE THREAD

**Issue by oogasawa** [oogasawa/nigsc_homepage2#58]
@akatsumata ニュースを追加したので本番環境に上げておいてください。
個人ゲノム解析区画のログインの仕方のところがよく読むとわかりにくいので(HCPtoolsの記事と同じような症状）、これは別のissueとしてやらないといけません。

**Comment by akatsumata** [comment]
本番環境に反映いたしました。
